# Generated by Django 2.1.7 on 2019-03-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_test', '0002_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.FileField(blank=True, upload_to='pics'),
        ),
    ]
